"""
International First Names Database
Contains first names from German and many international origins (Turkish, Polish,
Czech/Slovak, Serbian/Croatian, Romanian, Bulgarian, Russian/Ukrainian, Greek,
Albanian, Arabic) for identification during name parsing.
Used by process_excel.py to distinguish first names from last names.
"""

INTERNATIONAL_FIRST_NAMES = {
    # Male names (A-Z)
    'aaron', 'abdul', 'abdullah', 'abram', 'achim', 'adalbert', 'adam', 'adrian', 'ahmad', 'ahmed',
    'alain', 'alan', 'albert', 'albrecht', 'aldo', 'alexander', 'alexis', 'alf', 'alfred', 'alois',
    'alwin', 'amadeus', 'andre', 'andreas', 'andy', 'angelo', 'ansgar', 'anton', 'antonius', 'arne',
    'armin', 'arnold', 'arno', 'arthur', 'artur', 'august', 'augustin', 'axel',
    'baldur', 'baptist', 'barnabas', 'bartholomäus', 'bastian', 'benedikt', 'benjamin', 'benno', 'benny',
    'bernd', 'bernhard', 'bert', 'berthold', 'bertram', 'björn', 'bo', 'boris', 'bruno',
    'carl', 'carlos', 'carsten', 'christian', 'christof', 'christoph', 'christopher', 'claas', 'claudius',
    'claus', 'clemens', 'conny', 'conrad', 'konstantin', 'cornelius', 'cosimo', 'curt',
    'damian', 'daniel', 'danny', 'darko', 'david', 'denis', 'dennis', 'denny', 'derek', 'detlef',
    'detlev', 'dierk', 'dietbert', 'dieter', 'dietmar', 'dietrich', 'dino', 'dirk', 'dominic',
    'dominik', 'donald', 'dorian', 'douglas',
    'eckart', 'eckhard', 'eckhardt', 'edgar', 'edmund', 'eduardo', 'eduard', 'edward', 'edwin',
    'egbert', 'egon', 'eike', 'ekkehard', 'elias', 'elijah', 'elio', 'emanuel', 'emil', 'emilian',
    'emilio', 'emmanuel', 'enno', 'enrico', 'enzo', 'ephraim', 'erhard', 'eric', 'erich', 'erik',
    'ernest', 'ernst', 'erwin', 'eugen', 'ewald', 'ezra',
    'fabian', 'fabio', 'falko', 'felix', 'ferdinand', 'finn', 'florian', 'francesco', 'francis',
    'frank', 'franz', 'fred', 'fredi', 'frederic', 'frederick', 'fredrik', 'fridolin', 'friedrich',
    'friedhelm', 'fritz',
    'gabriel', 'georg', 'gerald', 'gerd', 'gerhard', 'gernot', 'gero', 'gert', 'gilbert', 'gino',
    'giorgio', 'giovanni', 'giuseppe', 'gordon', 'gottfried', 'gotthard', 'gregor', 'guido',
    'günter', 'günther', 'gustav', 'guy',
    'hagen', 'hajo', 'hakan', 'hannes', 'hanno', 'hans', 'harald', 'hardy', 'hartmut', 'hartwig',
    'hasso', 'hauke', 'heiko', 'heiner', 'heinrich', 'heinz', 'helge', 'hellmut', 'helmut', 'hendrik',
    'henning', 'henri', 'henrik', 'henry', 'herbert', 'hermann', 'heribert', 'hilmar', 'hinrich',
    'holger', 'horst', 'hubert', 'hubertus', 'hugo',
    'ian', 'ignaz', 'igor', 'ilias', 'immanuel', 'ingo', 'ingolf', 'isaac', 'ismail', 'ivan', 'ivo',
    'jacob', 'jakob', 'jan', 'janis', 'jann', 'jannik', 'jannis', 'jano', 'janosch', 'jared', 'jarl',
    'jarno', 'jaromir', 'jascha', 'jason', 'jean', 'jeremias', 'jeremy', 'jerome', 'jesse', 'joachim',
    'jochen', 'joe', 'joel', 'joey', 'johann', 'johannes', 'john', 'johnny', 'jonas', 'jonathan',
    'jordan', 'jorge', 'joris', 'jose', 'josef', 'joseph', 'joshua', 'josip', 'jost', 'joost',
    'jörg', 'jörn', 'juan', 'julian', 'julius', 'juri', 'jürgen', 'justus',
    'kai', 'kalle', 'karim', 'karl', 'karsten', 'kasimir', 'kaspar', 'kay', 'kenan', 'kenneth',
    'kenny', 'kevin', 'kilian', 'kim', 'kjell', 'klaas', 'klaus', 'klemens', 'knut', 'konrad',
    'konstantin', 'kornel', 'kolja', 'korbinian', 'kristian', 'kristof', 'kurt',
    'lars', 'laurence', 'laurens', 'laurent', 'lawrence', 'leander', 'lean', 'lee', 'leif', 'len',
    'lenn', 'lennard', 'lennart', 'lennie', 'lenny', 'lennox', 'lenz', 'leo', 'leon', 'leonard',
    'leonardo', 'leonhard', 'leopold', 'leroy', 'levi', 'liam', 'linus', 'lionel', 'logan', 'lorenz',
    'lorenzo', 'lothar', 'louis', 'luan', 'luc', 'luca', 'lucas', 'lucian', 'ludwig', 'luis', 'luiz',
    'luk', 'luka', 'lukas', 'luther', 'lutz',
    'magnus', 'maik', 'malte', 'manuel', 'manfred', 'marc', 'marcel', 'marco', 'marcus', 'marek',
    'marian', 'marijn', 'mario', 'marius', 'mark', 'marko', 'markus', 'marlon', 'marten', 'martin',
    'marvin', 'mathias', 'mathis', 'matias', 'matteo', 'matthäus', 'matthias', 'mattis', 'matti',
    'maurice', 'max', 'maximilian', 'maxim', 'mehmet', 'meinhard', 'melvin', 'merlin', 'mert',
    'michael', 'michel', 'mick', 'miguel', 'mike', 'milan', 'milo', 'miro', 'mirko', 'mischa',
    'moritz', 'murat', 'mustafa',
    'nathan', 'nathanael', 'neo', 'nevio', 'nico', 'nicolai', 'nicolas', 'niko', 'nikola', 'nikolai',
    'nikolaj', 'nikolas', 'nils', 'noah', 'noel', 'nolan', 'norman', 'norbert',
    'ole', 'olaf', 'oliver', 'oscar', 'oskar', 'oswald', 'otfried', 'othmar', 'otmar', 'otto', 'ottomar',
    'pablo', 'pascal', 'pasquale', 'patric', 'patrick', 'patricius', 'paul', 'peer', 'pepe', 'pedro',
    'peter', 'phil', 'philip', 'philipp', 'philippe', 'pierre', 'piet', 'pius',
    'quentin', 'quirin',
    'rafael', 'raimund', 'rainer', 'ralf', 'ralph', 'ramon', 'randy', 'raphael', 'raul', 'ray',
    'raymond', 'red', 'reiner', 'reinhard', 'reinhold', 'remo', 'rene', 'richard', 'rick', 'rico',
    'robert', 'roberto', 'robin', 'rocco', 'rod', 'roderic', 'roderick', 'rodger', 'rodion', 'rodney',
    'rodrigo', 'rolf', 'roman', 'ronald', 'ronny', 'rouven', 'roy', 'ruben', 'rudi', 'rudolf',
    'rudolph', 'rupert', 'ryan',
    'samir', 'samuel', 'sandro', 'santiago', 'sascha', 'sebastian', 'sem', 'semih', 'seppl', 'serge',
    'sergej', 'sergio', 'severin', 'siegbert', 'siegfried', 'siegmar', 'siegmund', 'sigismund',
    'sigmund', 'silvester', 'silvio', 'simon', 'sinan', 'sixtus', 'sören', 'stan', 'stanislav',
    'stefan', 'steffen', 'stephan', 'steve', 'steven', 'sven', 'svend', 'swen', 'sylvester',
    'tadeusz', 'tamino', 'tammo', 'tarık', 'ted', 'theo', 'theodor', 'thies', 'thilo', 'thomas',
    'thorben', 'thorsten', 'tiago', 'till', 'tillman', 'tilo', 'tim', 'timo', 'timofey', 'timon',
    'timothy', 'tino', 'titus', 'tizian', 'tiziano', 'tobias', 'tom', 'tomas', 'tommy', 'toni',
    'tony', 'torben', 'torge', 'torsten', 'tristan',
    'udo', 'ulf', 'ulrich', 'umberto', 'urban', 'urs', 'uwe',
    'valentin', 'veit', 'victor', 'viktor', 'vincenzo', 'vincent', 'vinzenz', 'vito', 'volker',
    'volkmar', 'waldemar', 'walter', 'wanja', 'werner', 'wieland', 'wiegand', 'wilfried', 'wilhelm',
    'willi', 'william', 'willy', 'winfried', 'wolf', 'wolfgang', 'wolfram',
    'xaver', 'yannic', 'yannick', 'yannik', 'yannis', 'yasin', 'youssef', 'yuri',
    'zacharias', 'zachary',

    # Female names (A-Z)
    'ada', 'adela', 'adelaide', 'adele', 'adelia', 'adelina', 'adeline', 'adina', 'adriana',
    'adriane', 'agathe', 'agatha', 'agnes', 'aida', 'aimee', 'alana', 'alara', 'alba', 'alberta',
    'albertina', 'albertine', 'aleida', 'alena', 'alessandra', 'alessia', 'alexa', 'alexandra',
    'alexandrine', 'alexia', 'alexis', 'alice', 'alicia', 'alida', 'alina', 'aline', 'alisa',
    'alissa', 'aliya', 'alyssa', 'alma', 'almut', 'alwina', 'alyssa', 'amanda', 'amalia', 'amalie',
    'amalia', 'amara', 'amelia', 'amelie', 'amy', 'ana', 'anastasia', 'andrea', 'andrina', 'angela',
    'angelica', 'angelika', 'angelina', 'angeline', 'angelique', 'anica', 'anika', 'anita', 'anja',
    'ann', 'anna', 'annabel', 'annabella', 'annabelle', 'annalena', 'annalisa', 'annamaria',
    'anne', 'annegret', 'anneliese', 'annelie', 'anneliese', 'annemarie', 'annerose', 'annett',
    'annette', 'anni', 'annica', 'annika', 'anny', 'anouk', 'antje', 'antonia', 'antonie', 'ariane',
    'arianna', 'ariana', 'arla', 'arlene', 'arlette', 'armgard', 'asta', 'astrid', 'aubrey', 'audrey',
    'augusta', 'auguste', 'augustina', 'aurora', 'ava', 'aveline', 'aylin', 'ayse',
    'babett', 'babette', 'barbara', 'beata', 'beate', 'beatrice', 'beatrix', 'belen', 'bella',
    'belle', 'belinda', 'benedetta', 'benita', 'berenice', 'bernadette', 'bernardine', 'berta',
    'bertha', 'bettina', 'betty', 'bianca', 'bianka', 'birgit', 'birgitta', 'birte', 'blanca',
    'blanche', 'brigid', 'brigida', 'brigitte', 'brigitta', 'brita', 'britta', 'brunhild',
    'brunhilde',
    'camilla', 'camille', 'candida', 'cara', 'caren', 'carina', 'carla', 'carlotta', 'carmela',
    'carmen', 'carola', 'carolin', 'caroline', 'carolyn', 'cassandra', 'catharina', 'catharine',
    'catherine', 'cathleen', 'cathrin', 'catrin', 'cecile', 'cecilia', 'celeste', 'celestina',
    'celia', 'celina', 'celine', 'chantal', 'charleen', 'charlene', 'charlotte', 'chiara', 'chloe',
    'christa', 'christel', 'christiana', 'christiane', 'christin', 'christina', 'christine',
    'cindy', 'claire', 'clara', 'clare', 'clarissa', 'claudia', 'claudine', 'clementine', 'cleo',
    'clothilde', 'coco', 'colette', 'concetta', 'connie', 'constance', 'constanze', 'cora', 'coralie',
    'cordelia', 'cordula', 'corinna', 'corinne', 'cornelia', 'cosima',
    'dagmar', 'dahlia', 'daisy', 'dana', 'daniela', 'danielle', 'daphne', 'davina', 'deborah',
    'delia', 'delphine', 'denise', 'desiree', 'diana', 'diane', 'dina', 'dinah', 'dora', 'doreen',
    'dorina', 'doris', 'dorit', 'dorothea', 'dorothee', 'dorothy',
    'ebba', 'edelgard', 'edeltraud', 'edeltraut', 'edith', 'edmunde', 'edna', 'edwina', 'elaine',
    'elena', 'elene', 'eleonora', 'eleonore', 'elfi', 'elfriede', 'eliana', 'eliane', 'elinor',
    'elisa', 'elisabeth', 'elise', 'eliska', 'eliza', 'elizabeth', 'elke', 'ella', 'ellen', 'elli',
    'ellie', 'ellina', 'elly', 'elma', 'elna', 'elodie', 'eloise', 'elsa', 'else', 'elsbeth',
    'elvira', 'elyse', 'elza', 'emanuela', 'emely', 'emeline', 'emilia', 'emilie', 'emily', 'emilya',
    'emma', 'emmanuelle', 'emmy', 'ena', 'enid', 'enya', 'erdmute', 'erica', 'erika', 'erin',
    'erna', 'ernesta', 'ernestine', 'esmeralda', 'esperanza', 'estella', 'estelle', 'esther',
    'ethel', 'etta', 'eugenia', 'eugenie', 'eulalia', 'eunice', 'eva', 'evangeline', 'eve',
    'evelina', 'eveline', 'evelyn', 'evelyne', 'evita',
    'fabienne', 'fabiola', 'faith', 'fanny', 'fatima', 'faye', 'fedora', 'felicia', 'felicitas',
    'felicity', 'feline', 'femke', 'fenja', 'fina', 'fine', 'fiona', 'fiore', 'flora', 'florence',
    'florentina', 'florentine', 'florina', 'florine', 'frances', 'francesca', 'franchesca',
    'francine', 'francisca', 'franziska', 'franka', 'frauke', 'freda', 'freddy', 'frederica',
    'frederike', 'freya', 'frida', 'frieda', 'friederike',
    'gabriela', 'gabriele', 'gabriella', 'gabrielle', 'gaby', 'gala', 'gale', 'garnet', 'gay',
    'gemma', 'genevieve', 'georgette', 'georgia', 'georgina', 'georgine', 'geraldine', 'gerda',
    'gerhild', 'gerlinde', 'gertraud', 'gertrude', 'gertrud', 'gia', 'gianna', 'giesela', 'gilda',
    'gillian', 'gina', 'ginette', 'gisela', 'giselle', 'gitta', 'giulia', 'giuliana', 'gladys',
    'gloria', 'grace', 'gražina', 'greta', 'grete', 'gretel', 'gudrun', 'gunda', 'gunhild',
    'gunilla', 'gundula', 'gunta', 'gunthild', 'gwen', 'gwendolin', 'gwendolyn',
    'hagar', 'hana', 'hanna', 'hannah', 'hannelore', 'harriet', 'hattie', 'hedy', 'heide', 'heidemarie',
    'heidi', 'heike', 'helen', 'helena', 'helene', 'helga', 'helge', 'hella', 'hellena', 'hella',
    'helma', 'helmina', 'helmine', 'henny', 'henrike', 'henrietta', 'henriette', 'henrika', 'hermine',
    'hermione', 'herta', 'hertha', 'hester', 'hetty', 'hilda', 'hilde', 'hildegard', 'hildegarde',
    'hilma', 'hiltraud', 'holly', 'hortense', 'hortensia', 'hulda',
    'ida', 'idaline', 'idun', 'ileana', 'ilena', 'ilka', 'ilona', 'ilsa', 'ilse', 'ima', 'imelda',
    'imke', 'imma', 'ina', 'india', 'ines', 'inga', 'inge', 'ingeborg', 'ingelore', 'inger',
    'ingrid', 'inka', 'inken', 'inna', 'io', 'ioana', 'iona', 'ira', 'irena', 'irene', 'irina',
    'iris', 'irma', 'irmgard', 'irmgardt', 'irmhild', 'irmtraud', 'irmtraut', 'iryna', 'isa',
    'isabel', 'isabela', 'isabella', 'isabelle', 'isadora', 'isalie', 'isolde', 'ivana', 'ivanka',
    'ivonne', 'ivy',
    'jacinta', 'jacqueline', 'jade', 'jamie', 'jana', 'jane', 'janelle', 'janet', 'janette', 'janice',
    'janina', 'janine', 'janis', 'janka', 'janna', 'janne', 'jannika', 'jaqueline', 'jasmin',
    'jasmina', 'jasmine', 'jayne', 'jean', 'jeanette', 'jeanie', 'jeanne', 'jeannette', 'jeannine',
    'jella', 'jemima', 'jena', 'jenifer', 'jenna', 'jenni', 'jennifer', 'jenny', 'jerusha',
    'jessica', 'jessie', 'jette', 'jill', 'joan', 'joana', 'joanna', 'joanne', 'jocelyn', 'jodie',
    'johanna', 'johanne', 'joleen', 'jolene', 'jolina', 'jolinda', 'jolyn', 'jordana', 'jordis',
    'josefa', 'josefin', 'josefina', 'josefine', 'josepha', 'josephina', 'josephine', 'josie',
    'josina', 'joslyn', 'joy', 'joyce', 'juana', 'jude', 'judith', 'judy', 'jule', 'julia', 'juliana',
    'juliane', 'julianna', 'julianne', 'julie', 'julienne', 'juliet', 'julietta', 'juliette', 'julika',
    'julina', 'june', 'juno', 'jutta',
    'kaja', 'kara', 'karen', 'karin', 'karina', 'karla', 'karlee', 'karlie', 'karly', 'karola',
    'karolina', 'karoline', 'karolyn', 'kate', 'katerina', 'katelynn', 'kath', 'katharina',
    'katharine', 'katherine', 'kathie', 'kathleen', 'kathrin', 'kathryn', 'kathy', 'katia', 'katja',
    'katrin', 'katriona', 'katy', 'katya', 'kay', 'kayla', 'kelly', 'kerstin', 'kiana', 'kim',
    'kimberly', 'kimberley', 'kira', 'kirstin', 'kirsty', 'klara', 'klaudia', 'konstanze', 'kora',
    'kordula', 'kornelia', 'kriemhild', 'kris', 'krista', 'kristin', 'kristina', 'kristine', 'kyra',
    'lara', 'larissa', 'laura', 'laureen', 'laurel', 'lauren', 'laurentia', 'lavinia', 'lea', 'leah',
    'leandra', 'leda', 'lee', 'leia', 'leila', 'lena', 'lene', 'leni', 'lenia', 'lenka', 'leona',
    'leonie', 'leonore', 'leontina', 'leontine', 'leopoldina', 'leopoldine', 'leslie', 'lesley',
    'leta', 'letizia', 'levke', 'lia', 'liana', 'liane', 'lidia', 'liesa', 'liesbeth', 'liesel',
    'lieselotte', 'ligia', 'lila', 'lili', 'lilia', 'lilian', 'liliana', 'liliane', 'lilianna',
    'lilla', 'lilli', 'lillian', 'lilly', 'lily', 'lina', 'linda', 'lindsay', 'lindsey', 'lindy',
    'linette', 'linnea', 'lisa', 'lisar', 'liselotte', 'lisette', 'lisl', 'lissy', 'liv', 'livia',
    'liz', 'liza', 'lizbeth', 'lizzie', 'lizzy', 'lodovica', 'loes', 'lola', 'loni', 'lora', 'loredana',
    'loreley', 'loren', 'lorena', 'lorenz', 'loretta', 'lorna', 'lorraine', 'lotta', 'lotte', 'lottie',
    'lou', 'louisa', 'louise', 'luana', 'lucia', 'lucie', 'lucienne', 'lucile', 'lucille', 'lucinda',
    'lucy', 'ludmila', 'ludmilla', 'ludovica', 'ludwiga', 'luella', 'luisa', 'luise', 'lulu', 'luna',
    'lya', 'lydia', 'lynn', 'lynne',
    'mabel', 'mabelle', 'maddalena', 'madeleine', 'madeline', 'madlen', 'madlyn', 'madonna', 'magda',
    'magdalena', 'magdalene', 'maggie', 'mai', 'maia', 'maike', 'maja', 'malena', 'malia', 'malina',
    'malinka', 'malou', 'malvina', 'malvine', 'manda', 'mandy', 'manfred', 'manuela', 'mara',
    'marcela', 'marcella', 'marcia', 'mareike', 'maren', 'maresa', 'margaret', 'margareta',
    'margarete', 'margaretha', 'margarethe', 'margarita', 'margit', 'margo', 'margot', 'margret',
    'margrete', 'margreth', 'margrit', 'marguerite', 'mari', 'maria', 'mariama', 'marian', 'mariana',
    'mariann', 'marianna', 'marianne', 'maribel', 'marica', 'marie', 'mariel', 'mariella', 'marieluise',
    'marietta', 'mariette', 'marika', 'marilen', 'marilena', 'marilia', 'marilou', 'marilyn', 'marin',
    'marina', 'marinda', 'marine', 'marion', 'marisa', 'marise', 'marit', 'marita', 'maritza',
    'maritta', 'mariya', 'marje', 'marjolein', 'marjorie', 'marla', 'marlena', 'marlene', 'marley',
    'marlis', 'marlise', 'marly', 'marna', 'marsha', 'marta', 'martha', 'martina', 'martine',
    'mary', 'maryam', 'maryna', 'mathilda', 'mathilde', 'matilda', 'matilde', 'maud', 'maude',
    'maura', 'maureen', 'mauritia', 'mavis', 'maxima', 'maximiliana', 'maximiliane', 'maxine',
    'may', 'maya', 'mechthild', 'mechthilde', 'mechtild', 'meike', 'melanie', 'melinda', 'melisa',
    'melissa', 'melody', 'mercedes', 'mercy', 'meredith', 'merle', 'merryl', 'meta', 'mia',
    'michaela', 'michela', 'michele', 'michelle', 'mieze', 'mignon', 'mikaela', 'mila', 'milda',
    'milena', 'millicent', 'milly', 'milva', 'mimi', 'mina', 'minna', 'minnie', 'mira', 'miranda',
    'miriam', 'mirjam', 'mirka', 'mirta', 'mirthe', 'mitzi', 'moira', 'molly', 'mona', 'monica',
    'monika', 'monique', 'monna', 'muriel', 'mya', 'myriam', 'myrna', 'myrta', 'myrthe', 'myrtil',
    'myrtille',
    'nada', 'nadia', 'nadine', 'nadja', 'nadya', 'nancy', 'nanette', 'nanna', 'naomi', 'nastasia',
    'natacha', 'natalia', 'natalie', 'nataliya', 'natalya', 'natasha', 'natascha', 'nathalia',
    'nathalie', 'neda', 'nela', 'nelda', 'nell', 'nella', 'nelli', 'nellie', 'nelly', 'nena',
    'nessa', 'netti', 'nettie', 'nia', 'nicole', 'nicolette', 'nidia', 'nike', 'niki', 'nikita',
    'nikoleta', 'nina', 'ninette', 'nini', 'ninon', 'nita', 'nives', 'noa', 'noelie', 'noelle',
    'noemi', 'nola', 'nona', 'nora', 'norah', 'noreen', 'norina', 'norma', 'nova', 'nuala',
    'odelia', 'odessa', 'odette', 'odile', 'odilia', 'ofelia', 'oktavia', 'oktavie', 'olga',
    'olivia', 'olivie', 'oona', 'ophelia', 'ortrud', 'ortrun', 'ortwin', 'ottilia', 'ottilie',
    'pamela', 'paola', 'patricia', 'patrizia', 'paula', 'paulette', 'paulina', 'pauline', 'peggy',
    'penelope', 'penny', 'petra', 'petronella', 'petronilla', 'philippa', 'philippine', 'philomena',
    'phoebe', 'phyllis', 'pia', 'pierina', 'pierrette', 'piper', 'pippa', 'poldi', 'polly',
    'priscilla', 'prudence',
    'queenie', 'quinn',
    'rachel', 'rae', 'rafaela', 'ragna', 'ragnhild', 'raina', 'ramona', 'randi', 'raphaela', 'raquel',
    'rebecca', 'rebekka', 'regina', 'regine', 'reina', 'reinhild', 'reinhilde', 'rena', 'renata',
    'renate', 'rene', 'renee', 'resa', 'rhea', 'rhiannon', 'rhoda', 'rhodora', 'ricarda', 'richarda',
    'rieka', 'rika', 'riley', 'rina', 'rita', 'rivka', 'roberta', 'robin', 'robyn', 'roda', 'rohesia',
    'roisin', 'rolanda', 'roma', 'romana', 'romane', 'rome', 'romina', 'ronja', 'rosa', 'rosabel',
    'rosabella', 'rosalba', 'rosalia', 'rosalie', 'rosalind', 'rosalinda', 'rosaline', 'rosalyn',
    'rosamaria', 'rosamund', 'rosamund', 'rosanna', 'rosanne', 'rose', 'rosel', 'rosela', 'roselia',
    'roselinde', 'rosella', 'rosemaria', 'rosemarie', 'rosemary', 'rosetta', 'rosette', 'rosey',
    'rosie', 'rosina', 'rosine', 'rosita', 'rosmarie', 'roswitha', 'roxana', 'roxane', 'roxanna',
    'roxanne', 'roxy', 'ruby', 'ruth', 'ruthild', 'ruthilde',
    'sabina', 'sabine', 'sabrina', 'sadie', 'safiya', 'sally', 'salome', 'samantha', 'samira',
    'sandra', 'sandy', 'sanna', 'santina', 'saphira', 'sara', 'sarah', 'saskia', 'scarlett', 'selena',
    'selina', 'seline', 'selma', 'senta', 'serafina', 'seraphina', 'seraphine', 'serena', 'sevda',
    'shana', 'shane', 'shanna', 'shannon', 'sharon', 'shauna', 'shawn', 'shawnee', 'shayla', 'sheena',
    'sheila', 'shelly', 'shelby', 'sheridan', 'sherry', 'sheryl', 'shirley', 'sibylla', 'sibylle',
    'sidonia', 'sidonie', 'sienna', 'siegburga', 'sieghild', 'sieglinde', 'siegrid', 'siglinde',
    'sigrid', 'sigrun', 'silvana', 'silvia', 'silvie', 'silke', 'simona', 'simone', 'sina', 'sinaida',
    'siobhan', 'sissy', 'sofia', 'sofie', 'solange', 'soledad', 'solveg', 'solveig', 'sonja', 'sonya',
    'sophia', 'sophie', 'stacey', 'stacy', 'stefanie', 'steffi', 'stella', 'stephanie', 'stephany',
    'sue', 'sunny', 'susan', 'susana', 'susann', 'susanna', 'susanne', 'suse', 'susette', 'susi',
    'susie', 'susy', 'suzan', 'suzanna', 'suzanne', 'suzette', 'suzie', 'suzy', 'svea', 'svenja',
    'svetlana', 'sybil', 'sybille', 'sydney', 'sylke', 'sylva', 'sylvia', 'sylvie',
    'tabea', 'tabitha', 'talia', 'talida', 'talisa', 'talita', 'tamara', 'tamia', 'tamika', 'tammara',
    'tammy', 'tania', 'tanja', 'tanya', 'tara', 'taryn', 'tasha', 'tasja', 'tatiana', 'tatjana',
    'tatyana', 'tavia', 'taylor', 'tea', 'teodora', 'tera', 'teresa', 'terese', 'teresia', 'teresita',
    'terry', 'tess', 'tessa', 'thea', 'theda', 'thekla', 'thelma', 'theodora', 'theodore', 'theresa',
    'therese', 'theresia', 'thora', 'thyra', 'tia', 'tiana', 'tiffany', 'tilda', 'tilde', 'tilla',
    'tilly', 'tina', 'tine', 'tinka', 'tita', 'tiziana', 'tomke', 'toni', 'tonia', 'tonja', 'tora',
    'tracy', 'traude', 'traudel', 'traute', 'tricia', 'trina', 'trine', 'trinity', 'trish', 'trisha',
    'trixie', 'trudy', 'trudi',
    'ulla', 'ulrica', 'ulricke', 'ulrika', 'ulrike', 'undine', 'ursel', 'ursula', 'urszula', 'ursule',
    'uta', 'ute',
    'valentina', 'valeria', 'valerie', 'valery', 'valerya', 'valeska', 'vanda', 'vanessa', 'vanja',
    'vea', 'velma', 'venda', 'venetia', 'venita', 'venus', 'vera', 'verena', 'verina', 'verity',
    'verna', 'veronika', 'veronica', 'vicky', 'victoria', 'viktoria', 'vilhelmina', 'vilma',
    'vincenza', 'viola', 'violet', 'violetta', 'violette', 'virginia', 'virginie', 'vita', 'viva',
    'vivian', 'viviana', 'viviane', 'vivianna', 'vivianne', 'vivien', 'vivienne', 'vroni', 'vronique',
    'waleska', 'walburga', 'walburgis', 'walda', 'waldtraut', 'wally', 'waltraud', 'waltraut',
    'waltraute', 'wanda', 'wendela', 'wendelin', 'wendy', 'werner', 'wiebke', 'wilhelmina', 'wilhelmine',
    'willa', 'wiltrud', 'wiltrude', 'wilma', 'winifred', 'wioletta',
    'xanthe', 'xaver', 'xenia', 'xiomara',
    'yael', 'yara', 'yasmin', 'yasmina', 'yasmine', 'yelena', 'yolanda', 'yolande', 'yolanthe',
    'yvette', 'yvonne',
    'zara', 'zelda', 'zelia', 'zelma', 'zena', 'zenaide', 'zenia', 'zeta', 'zinaida', 'zita', 'zoe',
    'zoey', 'zona', 'zora', 'zoya', 'zsa', 'zsazsa', 'zula',

    # Common diminutives and variations
    'adi', 'alex', 'anke', 'benni', 'charly', 'conny', 'eli', 'franzi', 'freddy', 'gabi', 'gitti',
    'gretchen', 'gretel', 'hansi', 'heinzi', 'henny', 'jenny', 'jessi', 'jimmy', 'jonny', 'julia',
    'kai', 'kati', 'kira', 'kris', 'leo', 'liesl', 'lisa', 'lissi', 'loui', 'luise', 'magda', 'mani',
    'manu', 'michi', 'nicki', 'niki', 'olli', 'peti', 'reni', 'resi', 'ronni', 'rudi', 'sami',
    'sandi', 'sascha', 'seppi', 'steffi', 'susi', 'tina', 'tine', 'tobi', 'toni', 'uschi', 'vicky',
    'vivi', 'willy',

    # Additional German names (less common but valid)
    'irmgard', 'irmtraud', 'irmhild', 'rainer', 'reiner', 'raimer', 'raeiner', 'moritz', 'lothar', 'waltraud',
    'hildegard', 'hedwig', 'elfriede', 'adelheid', 'erika', 'lotte', 'christa', 'gerda', 'marlies',
    'hannelore', 'monika', 'renate', 'brigitte', 'ingeborg', 'sigrid', 'gudrun', 'roswitha',
    'gerhard', 'helmut', 'dieter', 'günter', 'werner', 'horst', 'hartmut', 'manfred', 'siegfried',
    'wilfried', 'friedhelm', 'eckhard', 'arno', 'arnulf', 'berthold', 'gerd', 'ulrich', 'dietmar',
    'ludger', 'alfons', 'gisbert', 'nicola', 'gisa', 'gisela', 'andree', 'andre', 'johnes', 'baris',
    'bahattin', 'sefer', 'dimitri', 'gerard', 'arnoldas', 'wilhem', 'begritte', 'hansjürgen',
    'maren', 'cathrin', 'hartmut', 'joachim', 'wilhelmine', 'bertold', 'arndt', 'egbert',
    'friedemann', 'gerwin', 'gotthard', 'günther', 'hieronymus', 'joachim', 'jörg', 'jürgen',
    'klemens', 'leonhard', 'maximilian', 'nikolaus', 'ottmar', 'philipp', 'raimund', 'reinhard',
    'rudolf', 'siegmund', 'theodor', 'tilman', 'valentin', 'wernher', 'willibald', 'wolfram',

    # Turkish male names
    'hamdi', 'onur', 'salih', 'ahmet', 'mehmet', 'mustafa', 'ali', 'hasan', 'hüseyin', 'ibrahim',
    'baris', 'barış', 'bahattin', 'sefer', 'celal', 'celalettin', 'esat', 'esad',
    'murat', 'emre', 'burak', 'kemal', 'cemal', 'ercan', 'hakan', 'kadir', 'cem', 'fatih',
    'yusuf', 'ömer', 'osman', 'ismail', 'ramazan', 'bayram', 'serkan', 'erdem', 'volkan', 'tolga',
    'bulent', 'bülent', 'cengiz', 'erdal', 'engin', 'erol', 'fevzi', 'ferhat', 'furkan', 'güven',
    'halil', 'harun', 'hayri', 'hikmet', 'hulusi', 'hüsnü', 'ilhan', 'ilyas', 'kaan', 'kamil',
    'koray', 'levent', 'lokman', 'mahmut', 'mesut', 'mevlüt', 'metin', 'muzaffer', 'necati',
    'nedim', 'nihat', 'nuri', 'oktay', 'orhan', 'ozan', 'resul', 'ridvan', 'rıfat', 'sait',
    'selim', 'serhat', 'sinan', 'süleyman', 'şükrü', 'tayfun', 'tarik', 'tarık', 'tuncay',
    'turan', 'uğur', 'ümit', 'vedat', 'veysel', 'yasin', 'yilmaz', 'yıldız', 'zeki', 'ziya',

    # Turkish female names
    'fatma', 'ayşe', 'emine', 'zeynep', 'elif', 'büşra', 'özlem', 'selin', 'pinar', 'pınar',
    'yasemin', 'tulin', 'tülin', 'nurcan', 'nuray', 'hatice', 'gülten', 'gülay', 'filiz',
    'esra', 'dilek', 'derya', 'deniz', 'canan', 'bahar', 'arzu', 'aylin', 'aynur', 'aysun',
    'aysel', 'asli', 'aslı', 'ahu', 'berrin', 'binnur', 'birsen', 'çiğdem', 'dilara', 'duygu',
    'ebru', 'eda', 'fadime', 'figen', 'gönül', 'gülşah', 'gülsüm', 'gülnur', 'hacer', 'hülya',
    'ilknur', 'ipek', 'kader', 'leyla', 'melek', 'meltem', 'merve', 'mihriban', 'müge', 'müzeyyen',
    'nagihan', 'nalan', 'nazan', 'nazlı', 'nergiz', 'nermin', 'nesrin', 'nihal', 'nilüfer',
    'nuriye', 'özge', 'özgül', 'rukiye', 'sabire', 'sacide', 'safiye', 'seher', 'semra', 'şerife',
    'sibel', 'songül', 'sultan', 'şule', 'tuba', 'ülkü', 'ümmü', 'vildan', 'zeliha', 'zübeyde',

    # Polish names (male)
    'andrzej', 'krzysztof', 'wojciech', 'piotr', 'grzegorz', 'marek', 'tomasz', 'zbigniew',
    'dariusz', 'mariusz', 'arkadiusz', 'bartosz', 'bartłomiej', 'bogdan', 'boguslaw', 'bronislaw',
    'czeslaw', 'damian', 'dominik', 'eugeniusz', 'franciszek', 'jacek', 'jaroslaw', 'jarek',
    'jerzy', 'józef', 'kamil', 'kazimierz', 'konrad', 'krystian', 'leszek', 'lukasz', 'łukasz',
    'maciej', 'marcin', 'marian', 'miroslaw', 'norbert', 'patryk', 'pawel', 'paweł', 'przemek',
    'przemyslaw', 'radoslaw', 'rafal', 'rafał', 'ryszard', 'slawomir', 'stanislaw', 'szymon',
    'tadeusz', 'waldemar', 'witold', 'wlodzimierz', 'zenon', 'zygmunt',

    # Polish names (female)
    'agnieszka', 'małgorzata', 'malgorzata', 'katarzyna', 'anna', 'barbara', 'ewa', 'krystyna',
    'beata', 'dorota', 'joanna', 'jolanta', 'halina', 'irena', 'danuta', 'alicja', 'bożena',
    'elżbieta', 'elzbieta', 'grażyna', 'grazyna', 'jadwiga', 'janina', 'monika', 'natalia',
    'patrycja', 'paulina', 'renata', 'sylwia', 'teresa', 'urszula', 'wanda', 'zofia', 'zuzanna',

    # Czech/Slovak names (male)
    'jiří', 'jiri', 'pavel', 'jan', 'martin', 'petr', 'tomáš', 'tomas', 'jaroslav', 'miroslav',
    'david', 'michal', 'ondrej', 'ondřej', 'radek', 'stanislav', 'vladimír', 'vladimir', 'zdeněk',
    'zdenek', 'ladislav', 'frantisek', 'frantiek', 'oldrich', 'oldřich', 'vaclav', 'václav',

    # Czech/Slovak names (female)
    'jana', 'petra', 'marie', 'eva', 'lucie', 'hana', 'veronika', 'alena', 'lenka', 'tereza',
    'katerina', 'kateřina', 'ivana', 'marketa', 'markéta', 'monika', 'renata', 'zuzana', 'blanka',
    'darina', 'dagmar', 'jitka', 'libuse', 'libuše', 'ludmila', 'marta', 'milena', 'miroslava',
    'olga', 'pavla', 'radka', 'ruzena', 'růžena', 'vera', 'věra', 'vlasta',

    # Serbian/Croatian/Bosnian names (male)
    'darko', 'goran', 'marko', 'milan', 'dragan', 'dejan', 'nenad', 'zoran', 'bojan', 'sasa',
    'saša', 'aleksandar', 'branko', 'branislav', 'dalibor', 'damir', 'danijel', 'denis', 'djordje',
    'đorđe', 'dubravko', 'dusan', 'dušan', 'filip', 'gordan', 'igor', 'ilija', 'ivan', 'ivica',
    'josip', 'jurica', 'krešimir', 'kresimir', 'luka', 'mario', 'marin', 'marinko', 'matej',
    'mirko', 'mladen', 'nebojša', 'nebojsa', 'nikola', 'predrag', 'radoslav', 'ranko', 'ratko',
    'slavko', 'slobodan', 'srđan', 'srdan', 'stjepan', 'tihomir', 'tomislav', 'velimir', 'vlado',
    'zdravko', 'zelimir', 'željko', 'zeljko', 'zlatko', 'zvonimir', 'zvonko',

    # Serbian/Croatian/Bosnian names (female)
    'maja', 'bojana', 'ana', 'ivana', 'marina', 'vesna', 'sanja', 'jelena', 'snežana', 'snezana',
    'dragana', 'nataša', 'natasa', 'gordana', 'mirjana', 'zorica', 'branka', 'danijela', 'dijana',
    'dubravka', 'dunja', 'jadranka', 'jasmina', 'kristina', 'lidija', 'lucija', 'marija', 'martina',
    'milica', 'nikolina', 'renata', 'silvija', 'slavica', 'sonja', 'sunčana', 'tamara', 'tanja',
    'tihana', 'valentina', 'vanja', 'vedrana', 'vera', 'zrinka',

    # Romanian names (male)
    'bogdan', 'florin', 'mihai', 'cristian', 'ionut', 'ionuț', 'adrian', 'andrei', 'cosmin',
    'catalin', 'cătălin', 'claudiu', 'corneliu', 'costel', 'dan', 'daniel', 'dinu', 'dragos',
    'dragoș', 'dumitru', 'george', 'gheorghe', 'georgian', 'horia', 'iancu', 'iulian', 'iuliu',
    'laurentiu', 'laurențiu', 'liviu', 'lucian', 'marian', 'marius', 'nicolae', 'octavian',
    'radu', 'razvan', 'răzvan', 'relu', 'robert', 'romulus', 'sergiu', 'silviu', 'sorin',
    'stefan', 'ștefan', 'tiberiu', 'traian', 'tudor', 'valentin', 'viorel',

    # Romanian names (female)
    'alina', 'cristina', 'ioana', 'mihaela', 'andreea', 'ana', 'camelia', 'carmen', 'claudia',
    'corina', 'cosmina', 'daniela', 'diana', 'elena', 'gabriela', 'georgiana', 'ileana', 'iulia',
    'larisa', 'laura', 'lavinia', 'liliana', 'luminita', 'luminița', 'madalina', 'mădălina',
    'magdalena', 'maria', 'mariana', 'nicoleta', 'oana', 'raluca', 'ramona', 'rodica', 'roxana',
    'silvia', 'simona', 'sorina', 'stefania', 'ștefania', 'teodora', 'valentina', 'veronica', 'viorica',

    # Bulgarian/Macedonian names (male)
    'georgi', 'ivan', 'dimitar', 'plamen', 'nikolay', 'hristo', 'boyan', 'borislav', 'borislaw',
    'boyko', 'evgeni', 'iliyan', 'kamen', 'lyubomir', 'milko', 'miroslav', 'petar', 'rumen',
    'stoyan', 'tihomir', 'todor', 'tsvetelin', 'vassil', 'valentin', 'viktor', 'vladislav',

    # Bulgarian/Macedonian names (female)
    'galina', 'irena', 'ivanka', 'kremena', 'kristina', 'lyudmila', 'mariana', 'milena', 'nadya',
    'natalia', 'radka', 'silviya', 'stela', 'svetla', 'tatyana', 'teodora', 'tsvetanka', 'vasilka',
    'veneta', 'violeta', 'yordanka', 'zorka',

    # Russian/Ukrainian names (male)
    'aleksei', 'aleksey', 'alexei', 'alexey', 'aleksander', 'anatoly', 'andrei', 'andrey', 'artem',
    'artyom', 'artur', 'boris', 'dmitri', 'dmitry', 'evgeny', 'fyodor', 'gennady', 'igor', 'ilya',
    'kirill', 'konstantin', 'leonid', 'maxim', 'mikhail', 'nikita', 'nikolai', 'oleg', 'pavel',
    'roman', 'ruslan', 'sergei', 'sergey', 'timur', 'vadim', 'valery', 'vasily', 'viktor', 'vitaly',
    'vladislav', 'volodymyr', 'vyacheslav', 'yaroslav', 'yuri', 'yury',

    # Russian/Ukrainian names (female)
    'anastasia', 'daria', 'darya', 'ekaterina', 'galina', 'irina', 'kseniya', 'ksenia', 'larisa',
    'liudmila', 'ludmila', 'marina', 'nadezhda', 'natalia', 'nataliya', 'natalya', 'olga', 'polina',
    'svetlana', 'tatiana', 'tatyana', 'ulyana', 'valentina', 'valeriya', 'veronika', 'viktoria',
    'yulia', 'yuliya', 'zoya',

    # Greek names (male)
    'alexandros', 'antonios', 'athanasios', 'christos', 'dimitrios', 'efstathios', 'eleftherios',
    'georgios', 'grigorios', 'ioannis', 'konstantinos', 'nikos', 'panagiotis', 'pantelis',
    'spyridon', 'stavros', 'theodoros', 'vasileios', 'vasilis', 'zacharias',

    # Greek names (female)
    'aikaterini', 'anna', 'artemis', 'athina', 'calliope', 'despina', 'dimitra', 'eleni', 'eleftheria',
    'evangelia', 'fotini', 'georgia', 'ioanna', 'irene', 'katerina', 'konstantina', 'kyriaki',
    'magdalini', 'maria', 'nikoleta', 'ourania', 'sofia', 'stavroula', 'vasiliki', 'xanthippi',

    # Albanian names (male)
    'artan', 'arben', 'besnik', 'bledar', 'blendi', 'dritan', 'edmond', 'eduart', 'emir', 'enis',
    'erion', 'erjon', 'ermal', 'fadil', 'fejzi', 'fisnik', 'flamur', 'florian', 'gentian', 'geri',
    'ilir', 'indrit', 'jeton', 'jetmir', 'krenar', 'kujtim', 'liridon', 'luani', 'lulzim', 'mentor',
    'ndue', 'petrit', 'pranvera', 'sabri', 'shpend', 'skender', 'sokol', 'taulant', 'valdrin',

    # Albanian names (female)
    'arta', 'aurora', 'besarta', 'blerta', 'bukurije', 'dafina', 'drita', 'elida', 'elira', 'elvana',
    'erinda', 'ermira', 'etleva', 'fatmire', 'flaka', 'flutura', 'genta', 'gentiana', 'gruia',
    'klaudia', 'klea', 'klodiana', 'lira', 'liridona', 'luljeta', 'lumturi', 'migena', 'mimoza',
    'mirelda', 'mirela', 'nora', 'pranvera', 'rinora', 'rozafa', 'rudina', 'saranda', 'shpresa',
    'sidita', 'sinela', 'vjosa', 'vjolca', 'zana',

    # Arabic/North African names (male, common in Germany)
    'abdelkarim', 'abdelkrim', 'abdulaziz', 'abdulhamid', 'abdallah', 'abdel', 'abdu', 'abid',
    'abu', 'adnan', 'ahmad', 'amir', 'anas', 'aymen', 'ayoub', 'ayman', 'aziz', 'bilal',
    'chahid', 'chaker', 'farid', 'faris', 'fehmi', 'fouad', 'habib', 'hafid', 'hamza', 'hatem',
    'hussein', 'idriss', 'imad', 'isam', 'issam', 'jalal', 'jamil', 'jihad', 'kamel', 'karim',
    'karima', 'khalid', 'khaled', 'lotfi', 'maher', 'mansour', 'marouane', 'mounir', 'mourad',
    'nacer', 'nabil', 'nadir', 'nassim', 'nizar', 'omar', 'rachid', 'ramzi', 'riad', 'ridha',
    'samir', 'sami', 'tarek', 'tariq', 'walid', 'wassim', 'yahya', 'yassine', 'yosef', 'younes',
    'yousef', 'zakaria', 'zakariya',

    # Arabic/North African names (female, common in Germany)
    'aida', 'aicha', 'amina', 'amira', 'asma', 'assia', 'chaima', 'dalila', 'dina', 'dunia',
    'fadoua', 'fairouz', 'fatiha', 'hafida', 'hajer', 'hanane', 'hiba', 'houda', 'imane', 'ines',
    'jamila', 'karima', 'khadija', 'khawla', 'laila', 'lamia', 'leila', 'lina', 'malika', 'manar',
    'maryam', 'meriem', 'monia', 'naima', 'nawal', 'nora', 'nour', 'noura', 'rahma', 'rajaa',
    'rania', 'rima', 'rim', 'safaa', 'salma', 'samia', 'samira', 'sara', 'selma', 'siham',
    'souad', 'soumia', 'wafa', 'widad', 'yasmina', 'zineb', 'zoulikha',

    # Tamil/Sri Lankan first names (male) — only given names, not patronymics
    'kandiah', 'krishnathashan', 'saravanabavan', 'thayaparan',
    'aravindan', 'chandrakumar', 'jeyarajah', 'kumarasamy', 'mahendran',
    'murugaiah', 'nithiyarajah', 'rajagopal', 'rajendran', 'ramachandran',
    'selvakumar', 'shanmugam', 'sivarajah', 'vijayaratnam',

    # Tamil/Sri Lankan names (female)
    'ambihai', 'arunthathi', 'kamala', 'kavitha', 'kohila', 'krishnaveni',
    'lalitha', 'malathi', 'meenakshi', 'nithyasri', 'parvathy', 'pushparani',
    'radha', 'saranya', 'saroja', 'subashini', 'suganya', 'thilaga', 'thilagavathi',
    'umarani', 'vasantha', 'vimala', 'yogambal',

    # Hungarian names (male)
    'ádám', 'adam', 'ákos', 'albert', 'árpád', 'attila', 'balázs', 'bence',
    'béla', 'bela', 'csaba', 'dániel', 'dávid', 'dénes', 'elemér', 'ernő',
    'erno', 'ferencz', 'gábor', 'gabor', 'géza', 'geza', 'gusztáv', 'gyula',
    'imre', 'istván', 'istvan', 'jenő', 'jeno', 'józsef', 'jozsef', 'károly',
    'karoly', 'kálmán', 'kalman', 'lajos', 'lászló', 'laszlo', 'levente',
    'lóránt', 'lorant', 'máté', 'mate', 'mihály', 'mihaly', 'miklós', 'miklos',
    'nándor', 'nandor', 'péter', 'peter', 'roland', 'sándor', 'sandor',
    'szabolcs', 'tamás', 'tamas', 'tibor', 'zoltán', 'zoltan', 'zsolt',

    # Hungarian names (female)
    'ágnes', 'agnes', 'anikó', 'aniko', 'aranyi', 'beáta', 'beata', 'borbála',
    'borbala', 'csilla', 'edit', 'enikő', 'eniko', 'éva', 'eva', 'erzsébet',
    'erzsebet', 'gyöngyi', 'gyongyi', 'hajnalka', 'ida', 'idikó', 'idiko',
    'ildikó', 'ildiko', 'irén', 'iren', 'judit', 'julianna', 'katalin',
    'klára', 'klara', 'krisztina', 'lilla', 'magdolna', 'mária', 'maria',
    'márta', 'marta', 'monika', 'nikoletta', 'noémi', 'noemi', 'orsolya',
    'piroska', 'réka', 'reka', 'rozália', 'rozalia', 'tímea', 'timea',
    'veronika', 'viktória', 'viktoria', 'zsuzsanna',

    # Kurdish names (male)
    'besir', 'beşir', 'berxwedan', 'baran', 'ciwan', 'dilaver', 'heval', 'hogir',
    'jiyan', 'karzan', 'kawa', 'kendal', 'Kurdistan', 'mazlum', 'mehmet', 'nawaf',
    'newroz', 'reber', 'rojhat', 'serdar', 'sinan', 'xelil', 'zelal', 'zinar',

    # Kurdish/Kurmanji names (female)
    'aygül', 'aygul', 'berfin', 'berivan', 'çiçek', 'cicek', 'delal', 'dilan',
    'gülbahar', 'gulbahar', 'gülistan', 'gulistan', 'helin', 'herdem', 'jiyan',
    'leyla', 'narin', 'newroz', 'rojda', 'ruken', 'seve', 'sosin', 'xezal', 'yasemin',
}
